openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /books/:
    get:
      operationId: listBooks
      description: ''
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: title
        required: false
        in: query
        description: title
        schema:
          type: string
      - name: authors
        required: false
        in: query
        description: authors
        schema:
          type: string
      - name: published_date
        required: false
        in: query
        description: published_date
        schema:
          type: string
      - name: categories
        required: false
        in: query
        description: categories
        schema:
          type: string
      - name: ratings_count
        required: false
        in: query
        description: ratings_count
        schema:
          type: string
      - name: average_rating
        required: false
        in: query
        description: average_rating
        schema:
          type: string
      - name: author
        required: false
        in: query
        description: author
        schema:
          type: string
      - name: category
        required: false
        in: query
        description: category
        schema:
          type: string
      - name: average_rating__gt
        required: false
        in: query
        description: average_rating__gt
        schema:
          type: string
      - name: average_rating__lt
        required: false
        in: query
        description: average_rating__lt
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=400&limit=100
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=200&limit=100
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Book'
          description: ''
      tags:
      - books
  /books/{id}/:
    get:
      operationId: retrieveBook
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique value identifying this book.
        schema:
          type: string
      - name: title
        required: false
        in: query
        description: title
        schema:
          type: string
      - name: authors
        required: false
        in: query
        description: authors
        schema:
          type: string
      - name: published_date
        required: false
        in: query
        description: published_date
        schema:
          type: string
      - name: categories
        required: false
        in: query
        description: categories
        schema:
          type: string
      - name: ratings_count
        required: false
        in: query
        description: ratings_count
        schema:
          type: string
      - name: average_rating
        required: false
        in: query
        description: average_rating
        schema:
          type: string
      - name: author
        required: false
        in: query
        description: author
        schema:
          type: string
      - name: category
        required: false
        in: query
        description: category
        schema:
          type: string
      - name: average_rating__gt
        required: false
        in: query
        description: average_rating__gt
        schema:
          type: string
      - name: average_rating__lt
        required: false
        in: query
        description: average_rating__lt
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: ''
      tags:
      - books
  /db/:
    post:
      operationId: createBook
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Q'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Q'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Q'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Q'
          description: ''
      tags:
      - db
components:
  schemas:
    Book:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        authors:
          type: array
          items:
            type: string
        published_date:
          type: string
          maxLength: 10
        categories:
          type: array
          items:
            type: string
        average_rating:
          type: number
          nullable: true
        ratings_count:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          nullable: true
        thumbnail:
          type: string
          format: uri
          maxLength: 200
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4]\\\
            d|1\\d?\\d?|[1-9]\\d?)(?:\\.(?:0|25[0-5]|2[0-4]\\d|1\\d?\\d?|[1-9]\\d?)){3}|\\\
            [[0-9a-f:.]+\\]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1\
            -\uFFFF0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1\
            -\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))(?::\\d{2,5})?(?:[/?#][^\\\
            s]*)?\\z"
      required:
      - title
      - authors
      - categories
    Q:
      type: object
      properties:
        q:
          type: string
          maxLength: 200
      required:
      - q
