# Generated by Django 3.2.4 on 2021-06-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.CharField(max_length=10)),
                ('thumbnail', models.URLField(blank=True)),
                ('ratings_count', models.IntegerField(null=True)),
                ('average_rating', models.FloatField(null=True)),
                ('authors', models.ManyToManyField(to='api.Author')),
                ('categories', models.ManyToManyField(to='api.Category')),
            ],
        ),
    ]
